version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - .:/app
    command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
